version : '3'
services:
  app:
    image: 'table-trek-docker-image'
    build:
      context: .
    container_name: 'table-trek-docker-container'
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tabletrekdb
      - SPRING_DATASOURCE_USERNAME=JoJoRamen
      - SPRING_DATASOURCE_PASSWORD=JoJoKaraMisso
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  db:
    image: postgres:latest
    container_name: TableTrekDB
    environment:
      - POSTGRES_USER=JoJoRamen
      - POSTGRES_PASSWORD=JoJoKaraMisso
      - POSTGRES_DB=tabletrekdb